name: lint

on: push

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@readium'

      - name: npm install & run lint
        run: |
          npm ci
          npm run lint
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
