name: tests

on: ["push", "pull_request"]

jobs:
  test:
    name: Run Tests in Browser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@readium'

      - name: npm install & run test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            npm ci
            npm run test
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
